### PR TITLE
Update rviz_visual_tools.cpp

### PR DESCRIPTION
**Pull request by jontromanab**
Changing the angles will change the opening angle of the cone. The function for creating cone has this unused variable angle, which is supposed to change the opening angle of the cone.

### CODE REVIEW

**Comment by davetcoleman** [comment]
This makes sense. Could you add a new cone test [here](https://github.com/davetcoleman/rviz_visual_tools/blob/kinetic-devel/src/rviz_visual_tools_demo.cpp#L212) that changes the angle so that we can visually verify that it does what is intended? Perhaps you could also update the screenshot of the test for the README?

**Comment by jontromanab** [comment]
@davetcoleman I have updated the test case with varying cone angles. Here is the screenshot
oie_9ux7qbblj7xi

**Comment by davetcoleman** [comment]
i don't think you committed the test

**Comment by jontromanab** [comment]
Sorry..I had committed to kinectic-devel. Now I have changed it in jade-devel

**Comment by davetcoleman** [comment]
i think this should stay in kinetic-devel.

**Comment by jontromanab** [comment]
so another pull request in kinetic-devel?

**Comment by davetcoleman** [comment]
this PR already targets kinetic, so you're good.

thanks!

**Pull request merged**
