### PR TITLE
Cone angle

### PR DESCRIPTION
**Pull request by jontromanab**
The function of cone has an unused variable "angle" which should be varying the opening angle of the cone. Please check and update the function.

### CODE REVIEW

**Comment by davetcoleman** [comment]
Seems like you are merging the jade branch into the indigo branch, there are a lot of commits of mine in this PR. Can you target this PR for jade instead?

**Comment by davetcoleman** [comment]
@mcevoyandy you added ``publishCone``, can you review it?

**Comment by jontromanab** [comment]
Do you want me to open a new PR with the jade branch?

**Comment by davetcoleman** [comment]
Yes please

**Pull request closed without merging**
